/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SimpleCheckbox {
        "checked": boolean;
        "toggle": () => Promise<boolean>;
    }
}
declare global {
    interface HTMLSimpleCheckboxElement extends Components.SimpleCheckbox, HTMLStencilElement {
    }
    var HTMLSimpleCheckboxElement: {
        prototype: HTMLSimpleCheckboxElement;
        new (): HTMLSimpleCheckboxElement;
    };
    interface HTMLElementTagNameMap {
        "simple-checkbox": HTMLSimpleCheckboxElement;
    }
}
declare namespace LocalJSX {
    interface SimpleCheckbox {
        "checked"?: boolean;
        "onChange"?: (event: CustomEvent<boolean>) => void;
    }
    interface IntrinsicElements {
        "simple-checkbox": SimpleCheckbox;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "simple-checkbox": LocalJSX.SimpleCheckbox & JSXBase.HTMLAttributes<HTMLSimpleCheckboxElement>;
        }
    }
}
